"""add content_modules

Revision ID: 4345b1ba2f08
Revises: 6c44a01aed58
Create Date: 2025-10-09 15:59:48.547587
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4345b1ba2f08"
down_revision = "6c44a01aed58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_modules",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("min_tier", sa.String(length=20), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_modules")
    # ### end Alembic commands ###
