"""add giftcard_code_to_invoices

Revision ID: 6c44a01aed58
Revises: f4777300af94
Create Date: 2025-10-09 15:14:52.821021
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c44a01aed58"
down_revision = "f4777300af94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("giftcard_code", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "giftcard_code")
    # ### end Alembic commands ###
